# Generated by Django 4.1.5 on 2025-10-27 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cliente'),
    ]

    # Intencionalmente vacío para evitar duplicar la creación de la columna 'estado'.
    # La migración 0004_pedidos_estado agrega físicamente la columna.
    operations = []
