# Generated by Django 4.1.5 on 2025-11-04 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='api.cliente'),
        ),
        migrations.AddField(
            model_name='productos',
            name='precio',
            field=models.IntegerField(default=0),
        ),
    ]
