# Generated by Django 4.1.5 on 2025-10-27 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='estado',
            field=models.CharField(choices=[('pendiente_pesos', 'Pendiente de Pesos'), ('listo_facturar', 'Listo para Facturar'), ('pendiente_confirmacion', 'Pendiente de Confirmación'), ('completado', 'Completado')], default='pendiente_pesos', max_length=50),
        ),
    ]
