# Generated by Django 4.1.5 on 2025-11-04 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_pedidos_estado'),
        ('api', '0004_pedidos_estado'),
    ]

    operations = [
    ]
