# Generated by Django 4.1.5 on 2025-11-09 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_merge_0003_pedidos_estado_0004_pedidos_estado'),
    ]

    operations = [
    ]
