# Generated by Django 4.1.5 on 2025-11-07 03:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_merge_0003_pedidos_estado_0004_pedidos_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensajeBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(default='low_stock', max_length=50)),
                ('texto', models.TextField()),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('audiencia', models.CharField(choices=[('all', 'all'), ('users', 'users'), ('groups', 'groups')], default='all', max_length=20)),
                ('destinatarios', models.ManyToManyField(blank=True, related_name='mensajes_destinatario', to=settings.AUTH_USER_MODEL)),
                ('grupos', models.ManyToManyField(blank=True, related_name='mensajes_bot', to='auth.group')),
            ],
        ),
        migrations.AddField(
            model_name='pedidos',
            name='facturado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productos',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productos',
            name='ultima_alerta_astock_bajo',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productos',
            name='umbral_minimo',
            field=models.IntegerField(default=20),
        ),
        migrations.CreateModel(
            name='MensajeLectura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leido_en', models.DateTimeField(auto_now_add=True)),
                ('mensaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.mensajebot')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('mensaje', 'usuario')},
            },
        ),
        migrations.AddField(
            model_name='mensajebot',
            name='leido_por',
            field=models.ManyToManyField(blank=True, related_name='mensajes_leidos', through='api.MensajeLectura', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mensajebot',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.productos'),
        ),
    ]
