# Generated by Django 4.1.5 on 2025-11-09 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_mensajebot_pedidos_facturado_en_productos_stock_and_more'),
        ('api', '0007_productos_stock'),
    ]

    operations = [
    ]
