# Generated by Django 4.1.5 on 2025-11-15 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_productos_stock'),
        ('api', '0008_merge_20251109_2021'),
    ]

    operations = [
    ]
