# Generated by Django 4.1.5 on 2025-11-23 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_merge_0006_productos_stock_0008_merge_20251109_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
