# Generated by Django 4.1.5 on 2025-10-27 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'permissions': [('view_pedidos', 'Puede ver los pedidos creados'), ('view_usuarios', 'Puede ver los usuarios existentes'), ('view_reportes', 'Puede ver los reportes de venta'), ('create_pedidos', 'Puede crear pedidos'), ('edit_pedidos', 'Puede editar pedidos'), ('delete_pedidos', 'Puede eliminar pedidos'), ('view_facturar', 'Puede ingresar a la vista de factura')]},
        ),
    ]
