# Generated by Django 4.1.5 on 2025-11-10 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'permissions': [('view_pedidos', 'Puede ver los pedidos creados'), ('view_usuarios', 'Puede ver los usuarios existentes'), ('view_reportes', 'Puede ver los reportes de venta'), ('create_pedidos', 'Puede crear pedidos'), ('edit_pedidos', 'Puede editar pedidos'), ('delete_pedidos', 'Puede eliminar pedidos'), ('view_facturar', 'Puede ingresar a la vista de factura'), ('view_clientes', 'Puede ver la vista de agregar cliente y lista de clientes'), ('agregar_clientes', 'Puede agregar clientes a la base de datos'), ('editar_clientes', 'Puede editar los datos de los clientes'), ('eliminar_clientes', 'Puede eliminar clientes'), ('edit_productos', 'Puede editar productos'), ('view_productos', 'Puede visualizar los productos')]},
        ),
    ]
